### ISSUE TITLE
No enabled connection

### ISSUE THREAD

**Issue by afm-mike** [ruflin/Elastica#1240] opened 2017-01-26 17:48 UTC
Ubuntu 16.04, latest Elasticsearch and Elastica, do you know what the issue is or what I may be doing wrong?  Any solutions for me, thanks!

Applying action ‘index’ on workspace Archive (87e22c282c95e50ccb628071fd21c12a)
<?xml version=”1.0″ encoding=”UTF-8″?><tree ><message type=”SUCCESS”>Indexation launched</message><consume_channel/></tree>

No enabled connection
PHP Fatal error: Uncaught Elastica\Exception\ClientException: No enabled connection in /usr/share/pydio/plugins/index.elasticsearch/vendor/ruflin/elastica/lib/Elastica/Connection/Strategy/Simple.php:28
Stack trace:
#0 /usr/share/pydio/plugins/index.elasticsearch/vendor/ruflin/elastica/lib/Elastica/Connection/ConnectionPool.php(98): Elastica\Connection\Strategy\Simple->getConnection(Array)
#1 /usr/share/pydio/plugins/index.elasticsearch/vendor/ruflin/elastica/lib/Elastica/Client.php(538): Elastica\Connection\ConnectionPool->getConnection()
#2 /usr/share/pydio/plugins/index.elasticsearch/vendor/ruflin/elastica/lib/Elastica/Client.php(657): Elastica\Client->getConnection()
#3 /usr/share/pydio/plugins/index.elasticsearch/vendor/ruflin/elastica/lib/Elastica/Index.php(295): Elastica\Client->request(’87e22c282c95e50…’, ‘HEAD’)
#4 /usr/share/pydio/plugins/index.elasticsearch/src/ElasticSearchIndexer.php(694): Elastica\Index->exists()
#5 /usr/share/pydio/plugins/index.elasticsearch/src/ElasticSearchIndexer.php(405): Pydio\Access\Ind in /usr/share/pydio/plugins/index.elasticsearch/vendor/ruflin/elastica/lib/Elastica/Connection/Strategy/Simple.php on line 28

**Comment by afm-mike** [comment] 2017-01-29 14:54
anybody?

**Comment by damienalexandre** [comment] 2017-01-29 18:35
Could you provide more information?

- where is hosted your elasticsearch node?
- does your PHP can contact this node?
- if you run everything on localhost, what does `curl localhost:9200` return?
- could you paste the code you use for this request?

**Comment by afm-mike** [comment] 2017-01-29 19:53
It is a single node, forget why I use the internal IP instead of localhost, but:

root@elasticlocal:/home/mike# curl 11.13.72.13:9200
{
  "name" : "elasticlocal",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "g1Ax20JPQsWP2E30B8SucQ",
  "version" : {
    "number" : "2.4.4",
    "build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
    "build_timestamp" : "2017-01-03T11:33:16Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}


To index within Pydio environment, I use:
php cmd.php -u=mike -p=xxxxxxxxxxxxxx -a=index -r=archive

Just tried again after a few days, and not sure what I changed in the interim, but now get this:

Applying action 'index' on workspace Archive (87e22c282j95e50ccb629071fd21c12a)
<?xml version="1.0" encoding="UTF-8"?><tree ><message type="ERROR">Deprecated: Elastica\Index::optimize() is deprecated and will be removed in further Elastica releases. Use Elastica\Query::forcemerge() instead.</message></tree>
<message type="SUCCESS">Indexation launched</message><consume_channel/>

PHP Fatal error:  Uncaught GuzzleHttp\Ring\Exception\RingException: cURL error 60: SSL certificate problem: unable to get local issuer certificate in /usr/share/pydio/core/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
Stack trace:
#0 /usr/share/pydio/core/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array)
#1 /usr/share/pydio/core/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #613)
#2 /usr/share/pydio/core/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array)
#3 /usr/share/pydio/core/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(54): GuzzleHttp\Ring\Client\CurlHandler->__invoke(Array)
#4 /usr/share/pydio/core/vendor/guzzlehttp/ringphp/src/Client/Middleware.php(30): GuzzleHttp\Ring\Client\Middleware::GuzzleHttp\Ring\Client\{closure}(Array)
#5 /usr/share/pydio/core/ven in /usr/share/pydio/core/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 51

**Comment by damienalexandre** [comment] 2017-01-29 21:52
Looks like your server lack the curl SSL certificates. You can found them here: https://curl.haxx.se/docs/caextract.html

This does not looks like an issue with Elastica, and this does not explain why your PHP tries to connect to Elasticsearch via HTTPS instead of the default HTTP.

**Comment by afm-mike** [comment] 2017-01-31 01:13
Hey Thanks!  Once I figure out how to set the PHP connection to Elasticsearch back to HTTP, I will try again.

**Comment by Tobion** [comment] 2017-03-12 17:44
Closing as not related to Elastica. Otherwise please give reproducible steps.

**Closed by Tobion** 2017-03-12 17:44 UTC

**Comment by teodorpav** [comment] 2017-08-05 13:46
Hi, please explain how connect back to HTTP?

'I figure out how to set the PHP connection to Elasticsearch back to HTTP, I will try again.'
