### ISSUE TITLE
Library is not PHP 7.0 ready.

### ISSUE THREAD

**Issue by rdohms** [ruflin/Elastica#1014] opened 2015-12-28 13:38 UTC
One of the main reasons for this is the `Bool` class which is now a reserved name.

Is there intent to make this compatible? I may be able to toss some developers at it, if its in the interest of the library.

**Comment by ewgRa** [comment] 2015-12-28 14:08
Bool is deprecated now, you can use BoolQuery or BoolFilter if you have PHP7.

Bool will be removed in next releases.

**Comment by ruflin** [comment] 2015-12-28 14:15
@rdohms Just saw also your issue here. Let us know in case we missed something here.

**Comment by zoglun** [comment] 2015-12-31 05:22
Notice that the master branch with Bool fix only support MW 1.27 &1.27+. Is there anyway for Elastica on MW1.26 with PHP7?

I tried 1.27.0-wmf.9 on my server and it does not work well.

**Comment by ruflin** [comment] 2015-12-31 07:52
@zoglun Sorry to ask, but what is MW?

**Comment by ruflin** [comment] 2015-12-31 08:09
Closing this issue. Please reopen if there is still an issue.

**Closed by ruflin** 2015-12-31 08:09 UTC

**Comment by reedy** [comment] 2015-12-31 12:55
MW = MediaWiki

> Bool is deprecated now, you can use BoolQuery or BoolFilter if you have PHP7.
> Bool will be removed in next releases.

So MW needs to make sure we're only using the BoolQuery/BoolFilter classes, and bump to the next release when it's available for PHP 7 support

I presume you mean version 3.0.0? Any idea of a release timescale?

**Comment by ruflin** [comment] 2015-12-31 13:07
Already version prior to 3.0.0 are compatible with PHP 7 and the classes above exist. The only thing you have to do is to make sure to replace all Bool classes with the appropriate new classes in MediaWiki. As far as I remember there are a few classes more which are not compatible and deprecated but have a correspondig class. So no need to wait for 3.0.0

**Comment by reedy** [comment] 2015-12-31 13:13
It seems only one extension is using the Bool classes, so I've proposed fixes for those in https://gerrit.wikimedia.org/r/261766

@zoglun Are you running the translate extension on your MW install?

**Comment by ruflin** [comment] 2015-12-31 13:15
@reedy :+1:

**Comment by zoglun** [comment] 2015-12-31 16:05
Oh, sorry for my ambiguous. I am asking for https://www.mediawiki.org/wiki/Extension:Elastica PHP7 support problem. I confused this Elastica with the Extension:Elastica from Mediawiki. 

Again, sorry for taking your time, and happy new year!

**Comment by ruflin** [comment] 2015-12-31 16:09
@zoglun no problem ;-) Happy new year

**Comment by reedy** [comment] 2015-12-31 16:48
https://github.com/wikimedia/mediawiki-extensions-Elastica is just a minimal wrapper around this repo

https://phabricator.wikimedia.org/T122686 is our task for fixing it up for anyone that ends up here looking for an answer :)


WMF is still on ElasticSearch 1.7.1, so made a request go get that bumped upto 1.7.4... Which allows us to use a newer version of Elastica

Bumping upto version 2 of ES is going to require more work etc...

Though, @zoglun does this library not work for you with the classes "existing"? Even if they're not used?

**Comment by zoglun** [comment] 2016-01-01 00:16
@reedy I didn't find any "existing" class error on Mediawiki wmf 1.27 Ver caused by this Elastica (master branch). 

The wmf Ver mediawiki sometimes behave Weird under PHP7. So we set up 3 more HHVM servers for new year trafics and would not try PHP 7 within half year until Mediawiki 1.27 release.

**Comment by reedy** [comment] 2016-01-01 06:14
We don't claim any PHP7 support, but we are working towards it. Remember, we're currently still supporting PHP 5.3.3 Anyway, it's offtopic over here, so we should move it to the phab task you filed.

We need specific errors to be able to attempt to fix it :)
