### ISSUE TITLE
Term filter and diacritics

### ISSUE THREAD

**Issue by giorrrgio** [ruflin/Elastica#933] opened 2015-09-16 16:05 UTC
I have a field with multiple mapping: 
```php
'model' => array('type' => 'multi_field', 'fields' => array(
    'model' => array('type' => 'string', 'index' => 'analyzed'),
    'original' => array('type' => 'string', 'index' => 'not_analyzed')
    )
)
```
and I need to filter on its original value with an exact match. Everything is okay until I have a value with diacritics:
```json
{"model": "4er Gran Coupé"}
```
This is my query:
```php
$elasticaQuery = new \Elastica\Query\Filtered();
$elasticaFilterBool = new \Elastica\Filter\Bool();
$term = new \Elastica\Filter\Term();
$term->setTerm('model.original', '4er Gran Coupé');
$elasticaFilterBool->addMust($term);
$elasticaQuery->setFilter($elasticaFilterBool);
```
This is the result query:
```json
{
    "term": {
        "model.model.original": "4er Gran Coup\u00e9"
    }
}
```
As you can see the diacritics are escaped, but this way the query won't match anything in the database. If I run the same query via CURL without the escaped diacritics I get my results.
Any clue?

**Comment by ewgRa** [comment] 2015-09-16 19:46
I think problem not in Elastica.

How you convert array to json?

try echo(json_encode($elasticaQuery->toArray(), JSON_UNESCAPED_UNICODE));

**Comment by ewgRa** [comment] 2015-09-16 19:49
Check JSON.php and #559

**Comment by im-denisenko** [comment] 2015-09-17 01:29
@giorrrgio Please specify php version and used transport.

**Comment by giorrrgio** [comment] 2015-09-17 07:59
@ewgRa I'm not doing array to json conversions, at least not directly. The query I reported was obtained from the Symfony profiler with FOSElasticaBundle.

@im-denisenko I'm using Elastica Http transport and PHP 5.6.4

If you need other details or a test case to reproduce the issue let me know!

**Comment by ewgRa** [comment] 2015-09-17 08:20
It is not about Elastica. it is about how FOSElasticaBundle show such queries:

https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/views/Collector/elastica.html.twig#L54

```
<code>{{ query.data|json_encode }}</code>
```

Better I think to create issue in FOSElasticaBundle

**Comment by giorrrgio** [comment] 2015-09-17 08:27
@ewgRa the point is: the query is not giving me expected results, and it's not related to the way the query itself is encoded and displayed by the FOSEB collector or the Symfony profiler.

**Comment by ewgRa** [comment] 2015-09-17 08:34
It is related.

Because Elastica actually run query without escaping unicode. As you say:  "If I run the same query via CURL without the escaped diacritics I get my results.". It is what Elastica do, runs it without escaping.

Than you go to profiler and profiler show you query with escaped unicode, but this is not what Elastica actually query to ES. If profiler will show you unescaped query, results will be expected?

This is how I see it. You can debug it yourself, I give a link with line, where is a problem on my mind.

**Comment by giorrrgio** [comment] 2015-09-17 08:41
@ewgRa 
> Because Elastica actually run query without escaping unicode.
My issue is that Elastica is not giving me the expected results. Let's remove the Profiler and the Collector from the equation, they are not relevant. 
I run a Term query with valid utf-8 diacritics inside it and I don't get the results I expect, if I run the same query with curl, I get my results. I will try to five a test case asap.

**Comment by ruflin** [comment] 2015-09-17 13:12
@ewgRa @giorrrgio I think the simplest to debug and check the problem is to add here a small integration test: https://github.com/ruflin/Elastica/blob/master/test/lib/Elastica/Test/Query/TermTest.php Like this we also see then directly what the issue is and know when its fixed. @giorrrgio Would you be able to open a pull request with this integration test?

**Comment by giorrrgio** [comment] 2015-09-17 14:21
@ruflin after deeper investigations I guess my problem is somewhere else in the chain, here's the test:
https://github.com/giorrrgio/Elastica/blob/diacritics-test/test/lib/Elastica/Test/Query/TermTest.php#L31
Making a PR right now

**Comment by ruflin** [comment] 2015-09-17 14:39
@giorrrgio See my comment on the pull request as this is more a unit test.

**Comment by giorrrgio** [comment] 2015-09-23 10:09
@ruflin I am sorry, Elastica here was not the issue, at all. The issue was with pagination, I had a bug the set a fixed offset that I didn't notice and it was always 10 (so that very particular search had only 1 result and with an offset of 10 produced 0 results). Sorry again and thanks for the patience!

**Comment by ruflin** [comment] 2015-09-23 14:31
@giorrrgio No problem, glad you found the problem. I still merged the pull request as it is always good to have an additional test inside.

**Closed by ruflin** 2015-09-23 14:31 UTC
