### ISSUE TITLE
 Wrong parameters for Exception

### ISSUE THREAD

**Issue by NadaBen** [ruflin/Elastica#1079] opened 2016-04-20 21:03 UTC
Hello, 
after install ElasticSearch with "conjecto / nemrod": "@dev", and when i try to execute nemrod:execute:populate --index=PhotoResource : it shows me this error

`

> Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php on line 41
> 
> Call Stack:
>     0.0002     239016   1. {main}() C:\wamp\www\test\app\console:0
>     0.0469    4329904   2. Symfony\Component\Console\Application->run() C:\wamp\www\test\app\console:27
>     0.0541    4585648   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
>     0.6019   18722104   4. Symfony\Component\Console\Application->doRun() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
>     0.6023   18723088   5. Symfony\Component\Console\Application->doRunCommand() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
>     0.6254   19329016   6. Symfony\Component\Console\Command\Command->run() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
>     0.6259   19330984   7. Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand->execute() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
>     1.4399   22566752   8. Conjecto\Nemrod\ElasticSearch\Populator->populate() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand.php:107
>     1.4399   22567048   9. Conjecto\Nemrod\ElasticSearch\Populator->getTypesToPopulate() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:84
>     1.6700   22791128  10. Conjecto\Nemrod\ElasticSearch\Resetter->resetIndex() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:212
>     1.6936   22791376  11. Elastica\Index->create() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Resetter.php:91
>     1.6936   22791776  12. Elastica\Index->request() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:250
>     1.6936   22791856  13. Elastica\Client->request() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:445
>     1.6938   22792680  14. Elastica\Request->send() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Client.php:587
>     1.6940   22793464  15. Elastica\Transport\Http->exec() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Request.php:167
>     1.8918   22843216  16. Elastica\Exception\ResponseException->__construct() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Transport\Http.php:145
>     1.8918   22843200  17. Exception->__construct() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php:41
> 
> 
> 
> 
>                                                                                
>   [Symfony\Component\Debug\Exception\FatalErrorException]                      
>   Error: Wrong parameters for Exception([string $exception [, long $code [, E  
>   xception $previous = NULL]]])                                                
>                                                                                
> 
> Exception trace:
>  () at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php:41
>  Exception->__construct() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php:41
>  Elastica\Exception\ResponseException->__construct() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Transport\Http.php:145
>  Elastica\Transport\Http->exec() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Request.php:167
>  Elastica\Request->send() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Client.php:587
>  Elastica\Client->request() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:445
>  Elastica\Index->request() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:250
>  Elastica\Index->create() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Resetter.php:91
>  Conjecto\Nemrod\ElasticSearch\Resetter->resetIndex() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:212
>  Conjecto\Nemrod\ElasticSearch\Populator->getTypesToPopulate() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:84
>  Conjecto\Nemrod\ElasticSearch\Populator->populate() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand.php:107
>  Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand->execute() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
>  Symfony\Component\Console\Command\Command->run() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
>  Symfony\Component\Console\Application->doRunCommand() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
>  Symfony\Component\Console\Application->doRun() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
>  Symfony\Component\Console\Application->run() at C:\wamp\www\test\app\console:27
>  {main}() at C:\wamp\www\test\app\console:0
> 
> nemrod:elastica:populate [--index [INDEX]] [--type [TYPE]] [--batch [BATCH]] [--no-reset] [--no-clear-cache] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
> Fatal error: Wrong parameters for Exception([string $exception [, long $code [, Exception $previous = NULL]]]) in C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php on line 41
> 
> Call Stack:
>     0.0002     239016   1. {main}() C:\wamp\www\test\app\console:0
>     0.0469    4329904   2. Symfony\Component\Console\Application->run() C:\wamp\www\test\app\console:27
>     0.0541    4585648   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
>     0.6019   18722104   4. Symfony\Component\Console\Application->doRun() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
>     0.6023   18723088   5. Symfony\Component\Console\Application->doRunCommand() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
>     0.6254   19329016   6. Symfony\Component\Console\Command\Command->run() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
>     0.6259   19330984   7. Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand->execute() C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
>     1.4399   22566752   8. Conjecto\Nemrod\ElasticSearch\Populator->populate() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand.php:107
>     1.4399   22567048   9. Conjecto\Nemrod\ElasticSearch\Populator->getTypesToPopulate() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:84
>     1.6700   22791128  10. Conjecto\Nemrod\ElasticSearch\Resetter->resetIndex() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:212
>     1.6936   22791376  11. Elastica\Index->create() C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Resetter.php:91
>     1.6936   22791776  12. Elastica\Index->request() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:250
>     1.6936   22791856  13. Elastica\Client->request() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:445
>     1.6938   22792680  14. Elastica\Request->send() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Client.php:587
>     1.6940   22793464  15. Elastica\Transport\Http->exec() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Request.php:167
>     1.8918   22843216  16. Elastica\Exception\ResponseException->__construct() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Transport\Http.php:145
>     1.8918   22843200  17. Exception->__construct() C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php:41
> 
> 
> 
> 
>                                                                                
>   [Symfony\Component\Debug\Exception\FatalErrorException]                      
>   Error: Wrong parameters for Exception([string $exception [, long $code [, E  
>   xception $previous = NULL]]])                                                
>                                                                                
> 
> Exception trace:
>  () at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php:41
>  Exception->__construct() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Exception\ResponseException.php:41
>  Elastica\Exception\ResponseException->__construct() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Transport\Http.php:145
>  Elastica\Transport\Http->exec() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Request.php:167
>  Elastica\Request->send() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Client.php:587
>  Elastica\Client->request() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:445
>  Elastica\Index->request() at C:\wamp\www\test\vendor\ruflin\elastica\lib\Elastica\Index.php:250
>  Elastica\Index->create() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Resetter.php:91
>  Conjecto\Nemrod\ElasticSearch\Resetter->resetIndex() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:212
>  Conjecto\Nemrod\ElasticSearch\Populator->getTypesToPopulate() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\ElasticSearch\Populator.php:84
>  Conjecto\Nemrod\ElasticSearch\Populator->populate() at C:\wamp\www\test\vendor\conjecto\nemrod\src\Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand.php:107
>  Conjecto\Nemrod\Bundle\ElasticaBundle\Command\PopulatorCommand->execute() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:259
>  Symfony\Component\Console\Command\Command->run() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:860
>  Symfony\Component\Console\Application->doRunCommand() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:192
>  Symfony\Component\Console\Application->doRun() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:92
>  Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at C:\wamp\www\test\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:123
>  Symfony\Component\Console\Application->run() at C:\wamp\www\test\app\console:27
>  {main}() at C:\wamp\www\test\app\console:0
> 
> nemrod:elastica:populate [--index [INDEX]] [--type [TYPE]] [--batch [BATCH]] [--no-reset] [--no-clear-cache] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command>
> `

**Comment by ruflin** [comment] 2016-04-21 11:31
This more looks like an error related to the FOSElastica bundle: https://github.com/FriendsOfSymfony/FOSElasticaBundle Could it be that you use an Elastica version incompatible with FOSElastica? Closing this as I don't think it is related to Elastica itself.

**Closed by ruflin** 2016-04-21 11:31 UTC

**Comment by GuiminZHOU** [comment] 2016-04-21 13:39
had same problem when I try to update ElasticaSearch from 1.7.4 to 2.2, 
the problem is: 
there is no version FosElasticaBundle for ElasticaSearch 2,
for the moment, FosElasticaBundle requires Elastica ~2.1, which is required ElasticaSearch 1.7.2
maybe just check ElasticaSearch version

ps: on github, Elastica Tag 2.3.1 requires 1.7.2, but on packagist, v2.3.1 requires 2.2.1, would be some mistake here?

**Comment by ruflin** [comment] 2016-04-21 14:14
@GuiminZHOU Do you know from where packagist takes this info? Where did you see this info?

**Comment by GuiminZHOU** [comment] 2016-04-21 14:18
https://packagist.org/packages/ruflin/elastica#2.3.1, at the bottom of the page, there is a table for dependancies, it seems that it's always the same

**Comment by ruflin** [comment] 2016-04-21 14:39
@GuiminZHOU Yep, doesn't seem like I can't do much about it. It takes the README from master independent on which version you click.

**Comment by GuiminZHOU** [comment] 2016-04-21 16:24
@ruflin , so normally, for ElasticaSearch 2, it returns a different response error array?
I have seen that for Elastica ~2.1, we use the function $response->getError() directly, while for Elastica ~3.0, we use the function $response->getErrorMessage() instead, add a json_encode() on $response->getError() if it's an array,
but for Elastica ~2.1, we can do the same thing, to make sure $response->getError() return a string instead of an array,

**Comment by ruflin** [comment] 2016-04-24 18:25
There are several BC breaks between ES 1.x and 2.x. The response error structure is just one major change. So finding a work around for the error will not solve your problem that the two versions are still not compatible with each other.
