### ISSUE TITLE
composer require 5.0.0-beta1 not found test dir

### ISSUE THREAD

**Issue by zplzpl** [ruflin/Elastica#1217] opened 2016-11-14 09:11 UTC
composer require 5.0.0-beta1 not found test dir

**Comment by ruflin** [comment] 2016-11-14 09:53
@zplzpl Can you share some more data? When did you see this error? What command did you run?

**Comment by zplzpl** [comment] 2016-11-14 10:01
i work in yii2 framework.

i run command:

composer require ruflin/Elastica:5.0.0-beta1 --ignore-platform-reqs

add "--ignore-platform-reqs" because of my php version is 5.5.x.

i look dir list.

not found test dir.

**Comment by p365labs** [comment] 2016-11-14 14:45
mm curious, even if php 5.5 is not yet supported, I've created a VM with Vagrant :
- ubuntu 14.04.5 LTS
- php 5.5.38-4+deb.sury.org~trusty+1
- composer 1.3-dev
- installed yii basic (composer create-project yiisoft/yii2-app-basic basic 2.0.10)
- composer require ruflin/Elastica:5.0.0-beta1 --ignore-platform-reqs -vvv

and everything seems ok, Elastica 5.0.0-beta1 has been installed correctly.

**Comment by ruflin** [comment] 2016-11-14 16:45
Also tried to reproduce this and couldn't. What do you exactly mean by "not found test dir"?

**Comment by Tobion** [comment] 2017-02-08 10:41
I think what @zplzpl means is that the `/test` folder is missing. But this is expected because it is not exported, see https://github.com/ruflin/Elastica/blob/master/.gitattributes#L15

If you need the test folder, e.g. as inspiration or for submitting PRs, you can use the `--prefer-source` option of composer. This issue can be closed.

**Comment by ruflin** [comment] 2017-02-09 15:38
Closing this one based on the feedback from @Tobion

**Closed by ruflin** 2017-02-09 15:38 UTC
