### ISSUE TITLE
Memory exhaustion issue

### ISSUE THREAD

**Issue by dbhattacharjee** [ruflin/Elastica#983] opened 2015-11-20 07:29 UTC
Hi,

In our application we have more than 7K records and we are pulling all of them to be exported via CSV/HTML format. Elastic search server is returning the data as expected but when it comes to JSON decode then it is throwing out of memory error.

``
[2015-11-20 07:17:17] emergency.EMERGENCY: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) {"type":1,"file":"/var/www/ABC/vendor/ruflin/elastica/lib/Elastica/JSON.php","line":34} []
``
Any help in resolving this issue ? 

Note: We want to avoid multiple calls to ES for division of work load.

**Comment by ruflin** [comment] 2015-11-20 07:32
@dbhattacharjee I would recommend to increase the memory size you assigned to PHP. As you send large batchs of documents it seems like 134MB is quite small. Any chance to change this in the php.ini?

**Comment by dbhattacharjee** [comment] 2015-11-20 07:37
@ruflin : By increasing memory limit this can be hidden at present. But we have 7K records in development/stag instance and will have much much more in production. 
I think it is not a core issue of this bundle rather json_decode() function. Is is possible to divide the input into smaller chunks before sending to json_decode() function or make internal sub-calls to ES to get response in batches and then combine them ?

**Comment by ruflin** [comment] 2015-11-20 07:43
Not sure what you mean by subcalls, but perhaps scan and scroll could help? https://www.elastic.co/guide/en/elasticsearch/guide/current/scan-scroll.html

Can you elaborate on what exactly the issue is with making multiple calls to es?

**Comment by dbhattacharjee** [comment] 2015-11-20 07:48
With multiple calls to ES, say for each 1K record, we need to change our existing code as well as have to store results from those call and combine them in our code.
In short, we do not want to make changes in our code. Is there scope of resolution from this bundle ?

**Comment by ewgRa** [comment] 2015-11-20 07:50
@dbhattacharjee There is a possibility that even raw response from Elasticsearch not fit your memory limit. What you will do in this case?

**Comment by dbhattacharjee** [comment] 2015-11-20 07:58
@ewgRa That is what I am asking here. This bundle and FosElastica bundles are very cleverly written, well tested and I can not outperform them by writing my own logic. 

Is it possible, if hits is more than  a large number (say 1K), then instead of parsing whole response at one shot, it performs scan and scroll or some other technique so that this memory error does not come.
Frankly, I am not expert of ES and I do not know scan-scroll or other things. I faced this in my development system and I am asking for help here.

**Comment by dbhattacharjee** [comment] 2015-11-20 08:02
Also, scan-scroll is saying to disable sorting (?). we can't do that either as customer need to view results in sorted order as chosen by them in the UI.

**Comment by ewgRa** [comment] 2015-11-20 08:17
I fear that your wishes more at application level and in any case you will need change application for this.

Even if there is will be stream processing of response, or transparent batch processing, there is no guaranty that it fit your memory limit. Ok, it will be parsed to array somehow, but array also will be big for your memory limit and we return to beginning of this story.

**Comment by ruflin** [comment] 2015-11-20 09:29
@dbhattacharjee I would highly recommend to make some changes at the application level. Elastica does not provide any magic around splitting up requests etc. It mainly maps the elasticsearch API. I assume json_decode puts all data into memory for decoding. Based on the assumption that your data is going to grow over time, you will hit the memory limit again and again.

For the sorting: The bigger your data set gets, the more expensive the sorting in case you want to return all data. Have a look at scroll: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html

I have the feeling that perhaps your problem could be handled in a different way. Retrieving large data sets at once from a search / storage system normally has its limitations. Can you describe a little bit the background of the application so we better understand what you are trying to do?

**Comment by dbhattacharjee** [comment] 2015-11-20 10:33
@ruflin Yes that is my guess too that we might encounter this problem time and again.
Here is the background :
We are storing records in ES. Now customer wants to have a list how many records are inserted into the application for last X days. In the application UI, we are showing records with pagination control.
Now, they want to export this list as HTML as well as CSV format. For this use case, we are pulling all the records that matched filter criteria and preparing the HTML/CSV.

We are using Symfony 2 framework for our application. Currently we are looking into this : http://obtao.com/blog/2014/03/elasticsearch-symfony-export-scan-scroll-functions/

Can you suggest anything to achieve this situation. Exact coding is not required, if we get some hint then it will help full for us.
Also thanks for replying to our queries so quickly :+1:

**Comment by ruflin** [comment] 2015-11-20 12:40
The question here is probably why they need the data in a csv file? Is it so they can go through the data themself in excel for visualisations? Here perhaps using [Kibana](https://www.elastic.co/products/kibana) on top of elasticsearch could help and give the customer direct access.

An alternative for the csv export could be to use [Logstas](https://www.elastic.co/products/logstash) csv plugin instead of feeding all the data through php: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-csv.html

**Comment by Lumbendil** [comment] 2015-11-20 14:27
Dipanjan if you're showing them the paginated data, exporting as CSV that
paginated data is pretty easy. You need to go through each of the pages,
and for each page write the records to a temp file. By using a temp file
and only processing a page worth of records at a time, you won't hit the
memory limit.

This same approach (writing to temp file) can also be used for html, by
writing first the headers (all the HTML previous to the first line of
results), then the html lines for each record on each page, and finally the
footer.

2015-11-20 13:40 GMT+01:00 Nicolas Ruflin <notifications@github.com>:

**Comment by dbhattacharjee** [comment] 2015-11-23 05:16
@Lumbendil Thanks for the hint. We are trying to implement this way now.

**Comment by ruflin** [comment] 2016-01-04 18:56
I'm closing this issue as there were no updates recently. Please reopen if needed.

**Closed by ruflin** 2016-01-04 18:56 UTC

**Comment by pthreat** [comment] 2021-10-21 00:07
Try to use generators, this is ridiculous in 2021
